version: "3.3"
services:
  server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=80
      - FCM_PRIVATE_KEY_ID
      - FCM_PRIVATE_KEY
      - ADAFRUIT_API_KEY
      - ADAFRUIT_USERNAME