name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "/home/ec2-user/app"
          SCRIPT_AFTER: |
            cd /home/ec2-user/app
            docker-compose down
            FCM_PRIVATE_KEY_ID=${{secrets.FCM_PRIVATE_KEY_ID}} FCM_PRIVATE_KEY=${{secrets.FCM_PRIVATE_KEY}} ADAFRUIT_API_KEY=${{secrets.ADAFRUIT_API_KEY}} ADAFRUIT_USERNAME=${{secrets.ADAFRUIT_USERNAME}} docker-compose up -d
