name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "/home/ec2-user/app"
          SCRIPT_AFTER: |
            export private_key_id=${{ secrets.FCM_PRIVATE_KEY }}
            cd /home/ec2-user/app
            docker-compose up
